### ISSUE TITLE
time editing

### ISSUE THREAD

**Issue by asimonov-hitachi** [facontidavide/rosbag_editor#1]
great tool!

one thing that can be improved is editing times of output file. at the moment i have to 'fight' the GUI to put the time i need. because it does some validation like end time cannot be after original end time. and then it restricts me how i can erase/add digits during editing

**Comment by facontidavide** [comment]
That is kind of weird. 

- of course end time can not be more than the original one, neither begin time can be earlier of the original one. That is intentional. https://github.com/facontidavide/rosbag_editor/blob/master/src/rosbag_editor.cpp#L136-L142

- About the way editing digits works... complain to Qt ;)

If you have any actual code change to suggest, please send a PR. The code is pretty trivial and easy to understand.

**Comment by asimonov-hitachi** [comment]
I think making it simple textbox without constant validation would be better than 'date/time' editbox.
then validating it before the main action.
but i do not know QT to make a change.

**Comment by facontidavide** [comment]
let's agree that we disagree about textbox vs date/time ;)

I will probably not make any change, since it might look easier for you but more complicated for others... including myself!

Cheers

**Comment by AlexSeongJu-sr** [comment]
@facontidavide 
thank you for sharing ur great work. I find it really useful for my work.

By the way, I also agree with asimonov-hitachi since from time to time, I need to type the 'invalid time' to finally type 'valid time'. 
It's not that I want to use some invalid time in the end, but it's that I get to type some invalid time in between typing. let's say that Im going to use 13:02:27 ~ 13:03:14 and at first it was 13:03:14 ~ 13:03:14, and the file starts at 13:02:25.  
with this restriction on valid time, I cannot set 13:02:27. if I change the starting point to 13:02:14, it is invalid because of starting time(13:02:25). if i change the starting point to 13:03:27, it is also invalid since it will be after the end point. 
If it is hard to understand, I recommend just use the GUI many times and u will find the inconveniences. 
what I recommend is that it would be better to use validation at the 'final save' time, not in between typing time.

**Comment by facontidavide** [comment]
I have a plan to improve that
